import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
Nuvoton/m460/Source/system_m460.c
""")

# add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
    src = src + ['Nuvoton/m460/Source/GCC/startup_M460.S']
elif rtconfig.CROSS_TOOL == 'keil':
    src = src + ['Nuvoton/m460/Source/ARM/startup_m460.s']
elif rtconfig.CROSS_TOOL == 'iar':
    src = src + ['Nuvoton/m460/Source/IAR/startup_M460.s']

path = [cwd + '/Nuvoton/m460/Include',]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
